workflows:
  ios_testflight:
    name: iOS â€¢ Tests + TestFlight
    max_build_duration: 90
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: appstore

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
